// Generated by CoffeeScript 1.9.3

/**
 * 将CSS的debug文件push到生产目录，并将引用到的背景图片自动添加hash后缀
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var Tools, _, _buildJs, _buildMap, _env, _hashLen, _imgMapPath, _jsDistPath, _jsMapPath, _jsPath, _mapPath, _stream, color, fs, gulp, gutil, jsCtl, jsImgRegex, path, plumber, setting, uglify;

fs = require('fs');

path = require('path');

_ = require('lodash');

gulp = require('gulp');

gutil = require('gulp-util');

uglify = require('uglify-js');

plumber = require('gulp-plumber');

Tools = require('./Tools');

setting = require('./setting');

color = gutil.colors;

_jsPath = setting.jsPath;

_jsDistPath = setting.distPath + 'js';

_mapPath = setting.mapPath;

_hashLen = setting.hashLength;

_jsMapPath = path.join(_mapPath, setting.jsMap);

_imgMapPath = path.join(_mapPath, setting.imgMap);

_env = setting.env;

jsImgRegex = /staticPath\s*\+\s*(('|")[\s\S]*?(.jpg|.png|.gif)('|"))/g;

_stream = function(files, cb, cb2) {
  return gulp.src(files).pipe(plumber({
    errorHandler: Tools.errrHandler
  })).on('data', function(res) {
    var _code, _minCode, _nameObj, _path, _source, imgMap;
    imgMap = Tools.getImgMap();
    _minCode = uglify.minify(res.contents.toString(), {
      fromString: true
    });
    _code = _minCode.code;
    _source = _code.replace(jsImgRegex, function(str, map) {
      var _str, key, val;
      console.log(map);
      key = map.replace(/(^\'|\")|(\'|\"$)/g, '').replace('/img/', '');
      val = _.has(imgMap, key) && _env !== 'dev' ? imgMap[key].distname : (map.indexOf('data:') > -1 || map.indexOf('about:') > -1 ? map : key + '?=t' + String(new Date().getTime()).substr(0, 8));
      _str = str.replace(key, val);
      console.log(_str);
      return _str;
    });
    _path = res.path.replace(/\\/g, '/').split(_jsPath)[1];
    _nameObj = path.parse(_path);
    _nameObj.hash = Tools.md5(_source);
    return cb(_nameObj, _source);
  }).on('end', cb2);
};

_buildJs = function(file, source) {
  Tools.mkdirsSync(path.dirname(file));
  return fs.writeFileSync(file, source, 'utf8');
};

_buildMap = function(map, cb) {
  var _newMap, _oldMap, jsonData;
  _oldMap = Tools.getJSONSync(_jsMapPath);
  _newMap = _.assign(_oldMap, map);
  jsonData = JSON.stringify(_newMap, null, 2);
  Tools.mkdirsSync(_mapPath);
  fs.writeFileSync(_jsMapPath, jsonData, 'utf8');
  return cb();
};


/*
 * js生产文件构建函数
 * @param {string} file 同gulp.src接口所接收的参数，默认是css源文件的所有css文件
 * @param {function} done 回调函数
 */

jsCtl = function(file, done) {
  var _count, _done, _file, jsMap;
  jsMap = {};
  _file = _jsPath + '**/*.js';
  if (typeof file === 'function') {
    _done = file;
  } else {
    _file = file || _file;
    _done = done || function() {};
  }
  setting.env !== 'dev' && gutil.log(color.yellow("Push js to dist."));
  _count = 0;
  return _stream(_file, function(obj, source) {
    var _distName, _distName2, _filePath, _filePath2, _source;
    _source = source;
    _distName = obj.dir + '/' + obj.name + '.' + obj.hash.substr(0, _hashLen) + obj.ext;
    _distName2 = obj.dir + '/' + obj.name + obj.ext;
    jsMap[obj.base] = {
      hash: obj.hash,
      distname: _distName.replace(/^\//, '')
    };
    _filePath = path.join(_jsDistPath, _distName);
    _filePath2 = path.join(_jsDistPath, _distName2);
    _buildJs(_filePath, _source);
    _buildJs(_filePath2, _source);
    return _count++;
  }, function() {
    return _buildMap(jsMap, function() {
      setting.env !== 'dev' && gutil.log(color.green(_count + " javascript files pushed!"));
      return _done();
    });
  });
};

module.exports = jsCtl;
