// Generated by CoffeeScript 1.9.3

/*
 * v.build config
 * @date 2014-12-2 15:10:14
 * @author pjg <iampjg@gmail.com>
 * @link http://pjg.pw
 * @version $Id$
 */
var _cdnDomain, _distName, _env, _host, _port, _root, _srcName, _staticPath, _tplOutName, args, cfg, path, ref;

path = require('path');

cfg = require('../config.json');

args = require('yargs').argv;

_root = process.env.INIT_CWD;

_env = (ref = args.e || args.env) != null ? ref : 'dev';

_srcName = cfg.srcPathName;

_distName = cfg.distPathName;

_tplOutName = cfg.tplOutName;

_host = 'localhost';

_port = 8800;

_cdnDomain = _env !== 'dev' ? cfg.envs[_env].cdnDomain : _host + ":" + _port;

_staticPath = ("//" + _cdnDomain + "/") + (_env !== 'dev' ? "" + _distName : "" + _srcName);

module.exports = {
  root: _root,
  env: _env,
  host: _host,
  port: _port,
  cdnDomain: _cdnDomain,
  staticPath: _staticPath,
  hashLength: cfg.hashLength,
  tplOutPath: _tplOutName + "/",
  distPath: _distName + "/",
  mapPath: _distName + "/map/",
  srcPath: _srcName + "/",
  jsPath: _srcName + "/js/",
  lessPath: _srcName + "/less/",
  cssPath: _srcName + "/css/",
  tplPath: _srcName + "/html/",
  imgPath: _srcName + "/img/",
  cssMap: "cssmap.json",
  imgMap: "imgmap.json",
  jsMap: "jsmap.json",
  watchFiles: [_srcName + "/css/**/*.css", _srcName + "/less/**/*.less", _srcName + "/img/**/*.{png,jpg,gif}", _srcName + "/html/**/*.{html,php,ejs}", _srcName + "/js/**/*.js", "!.DS_Store"]
};
